### ISSUE TITLE
Minify Html 

### ISSUE THREAD

**Issue by mhunesi** [luyadev/yii-helpers#5]
When minify html my template is broken. Actually there is no difference. I do not understand. I tried in other browsers but it didn't make any difference.

this is just one
**Minify Html:**

<img width="74" alt="image" src="https://user-images.githubusercontent.com/15876915/155236677-51388660-1086-4d08-b709-e3364beb2209.png">

```
<ul class=""><li class="language-li lang-element-item--active"><a class=" lang-link-item--active" href="https://www.gezer.com/category/erkek"><span class="flag-icon flag-icon-tr" style="font-size:15px"></span></a></li><li class="language-li"><a class="" href="https://www.gezer.com/category/erkek"><span class="flag-icon flag-icon-us" style="font-size:15px"></span></a></li></ul>
```

**No Minify:**

<img width="74" alt="image" src="https://user-images.githubusercontent.com/15876915/155236866-52e216d5-0cb5-4702-aa7d-e48c582c7ee4.png">

```
<ul class="">
<li class="language-li lang-element-item--active"><a class=" lang-link-item--active" href="https://www.gezer.com/category/erkek"><span class="flag-icon flag-icon-tr" style="font-size:15px"></span></a></li>
<li class="language-li"><a class="" href="https://www.gezer.com/category/erkek"><span class="flag-icon flag-icon-us" style="font-size:15px"></span></a></li>
</ul>
```

**Comment by nadar** [comment]
This is a css issue because of the whitespace before and after the `<li>`, therefore usually developers make `<ul><!-- --><li>...</li><!-- --><li></li><!-- --></ul>` around to ensure there are no whitespaces and then use css to make the paddings. The whitespace have been removed by the minify process.

**Comment by nadar** [comment]
I am going to close this issue because:

- Its a question (Please post questions at [forum.luya.io](https://forum.luya.io))
- Missing information's
- No more activity
- No one picked up the task (no Pull Request received)

If you think this is still important or there are more/new informations. **Please reopen the issue and let us know**.

If this is a problem or a feature you like to discuss, join our forum: [forum.luya.io](https://forum.luya.io). We try to keep our issue tracker as clean as possible in order to focus on active issues.
